#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GT911_TS)          += gt911_ts.o
#gt911_ts-objs := gt9xx_tool.o gt9xx_update.o gt9xx_ts.o
gt911_ts-objs := gt9xx_ts.o
