# Makefile.dtc
#
# This is not a complete Makefile of itself.  Instead, it is designed to
# be easily embeddable into other systems of Makefiles.
#
DTC_SRCS = \
	checks.c \
	data.c \
	dtc.c \
	flattree.c \
	fstree.c \
	livetree.c \
	srcpos.c \
	treesource.c \
	util.c \
	script_parser/iniparser.c \
	script_parser/dictionary.c \
	script_parser/script.c
	script_parser/script_to_dts.c

DTC_GEN_SRCS = dtc-lexer.lex.c dtc-parser.tab.c
DTC_OBJS = $(DTC_SRCS:%.c=%.o) $(DTC_GEN_SRCS:%.c=%.o)
