obj-$(CONFIG_AW_AXP) += axp-interface.o
obj-$(CONFIG_AW_AXP) += axp-mfd.o
obj-$(CONFIG_AW_AXP) += axp-rw.o
obj-$(CONFIG_AW_AXP) += axp-depend-init.o
obj-$(CONFIG_AW_AXP) += axp-depend-set.o
obj-$(CONFIG_AW_AXP) += axp-device.o
obj-$(CONFIG_AW_AXP) += axp-regu-device.o
obj-$(CONFIG_AW_AXP) += axp-debugfs.o
obj-$(CONFIG_AW_AXP) += axp-mem-device.o
obj-$(CONFIG_AXP_NMI_USED) += sunxi-nmi.o

#AXP81x
obj-$(CONFIG_AW_AXP81X) += axp-regu.o
obj-$(CONFIG_AW_AXP81X) += axp-irq.o
obj-$(CONFIG_AW_AXP81X) += axp-state.o
obj-$(CONFIG_AW_AXP81X) += axp-chg.o
obj-$(CONFIG_AW_AXP81X) += axp-filenode.o
obj-$(CONFIG_AW_AXP81X) += axp81x-board.o
obj-$(CONFIG_AW_AXP81X) += axp81x-board-device.o
obj-$(CONFIG_AW_AXP81X) += axp81x-regu.o
obj-$(CONFIG_AW_AXP81X) += axp81x-sply.o
obj-$(CONFIG_AW_AXP81X) += virtual81x.o
obj-$(CONFIG_AW_AXP81X) += virtual81x_dev.o
obj-$(CONFIG_AW_AXP81X) += axp81x-init.o

