#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_GT9XXF_TS)          += gt9xxf_ts.o
gt9xxf_ts-objs := gt9xx_update.o goodix_tool.o gt9xxf.o