#
# Makefile for sunxi specific clk
#

obj-y += clk-factors.o clk-periph.o 
#obj-y += clk-default.o
obj-${CONFIG_COMMON_CLK_DEBUG} += clk-debugfs.o
# obj-${CONFIG_ARCH_SUN8IW1} += clk-sun8iw1.o
# obj-${CONFIG_ARCH_SUN8IW3} += clk-sun8iw3.o
# obj-${CONFIG_ARCH_SUN8IW5} += clk-sun8iw5.o
# obj-${CONFIG_ARCH_SUN8IW6} += clk-sun8iw6.o
# obj-${CONFIG_ARCH_SUN8IW7} += clk-sun8iw7.o
# obj-${CONFIG_ARCH_SUN8IW8} += clk-sun8iw8.o
# obj-${CONFIG_ARCH_SUN8IW9} += clk-sun8iw9.o
# obj-${CONFIG_ARCH_SUN9IW1} += clk-sun9iw1.o
obj-${CONFIG_ARCH_SUN50IW1P1} += clk-sun50iw1.o
obj-${CONFIG_ARCH_SUN8IW10} += clk-sun8iw10.o
obj-${CONFIG_ARCH_SUN8IW11} += clk-sun8iw10.o
obj-$(CONFIG_SUNXI_AC100_CLK) +=clk-ac100.o
