


obj-y += sprite_cartoon.o
obj-y += sprite_progressbar/sprite_progressbar.o
obj-y += sprite_draw/sprite_draw.o
obj-y += sprite_char/sprite_char.o
obj-y += sprite_char/sfte/FontEngine.o
obj-y += sprite_char/sfte/sfte.o
