#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_AW5X06_TS)           += aw5306_ts.o
aw5306_ts-objs := AW5306_ts.o AW5306_userpara.o libAW5306
