#
# (C) Copyright 2000-2003
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307 USA
#


obj-y	+= clock.o
obj-y	+= timer.o
obj-y	+= board.o
obj-y	+= key.o
#obj-y	+= efuse.o
#obj-y	+= ss.o
obj-y	+= gic.o
obj-y	+= cpu_info.o
obj-y	+= reset.o

obj-y	+= usb/usbc.o
obj-y	+= usb/usbc_dev.o
obj-y	+= usb/usbc_dma.o
obj-y	+= usb/usbc_host.o
obj-y	+= usb/usbc_phy.o
obj-y	+= usb/usbc_resource.o

