#
# Makefile for the sensor:wq drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_BMA250)    += bma250.o
obj-$(CONFIG_SENSORS_SC7A30)   += sc7a30.o
obj-$(CONFIG_SENSORS_MMA7660)   += mma7660.o
obj-$(CONFIG_SENSORS_MMA7660)   += mxc622x.o
obj-$(CONFIG_SENSORS_MMA7660)   += mma8452.o
obj-$(CONFIG_SENSORS_MMA7660)   += mma865x.o

