#
# Makefile for the sunxi cpu budget cooling drivers.
#
obj-$(CONFIG_SUNXI_BUDGET_COOLING) += sunxi-budget.o 
sunxi-budget-y += sunxi-budget-cooling.o
sunxi-budget-y += sunxi-budget-cooling-dvfs.o
sunxi-budget-$(CONFIG_BUDGET_HOTPLUG_CPU) += sunxi-budget-cooling-hotplug.o